services:
  postgres-order:
    container_name: postgres-order
    image: postgres:16.2
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: order-service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5001:5432"
